baseurl = 'https://vordonez6.github.io/shaping-quantum/'
copyright = "© Victoria Ordonez"
enablerobotstxt = true
languagecode = "en-us"
pagination.pagerSize = 50
timezone = "America/New_York"
titlecasestyle = "Go"

[params.paige]
color = "#0d6efd"
external_link_new_tab = true
math = true
menu_style = "pills"
header_below = "Shaping Quantum"

[paige.date]
format = ".date_long"

#[languages.en]
#title = "Shaping Quantum"
#weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "Braids"
name = "Braids"
url = "/braids/"
weight = 20

[[languages.en.menu.main]]
identifier = "Knots"
name = "Knots"
url = "/knots/"
weight = 30

[[languages.en.menu.main]]
identifier = "Torus"
name = "Torus"
url = "/torus/"
weight = 50

[[languages.en.menu.main]]
identifier = "Jones Polynomial"
name = "Jones Polynomial"
url = "/jones-polynomial/"
weight = 40

# [[languages.en.menu.main]]
# identifier = "series"
# name = "Series"
# url = "/series/"
# weight = 70

# [[languages.en.menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 80

# [[languages.en.menu.main]]      
# identifier = "tags"
# name = "Tags"
# url = "/tags/"
# weight = 90

# [[languages.en.menu.main]]
# identifier = "search"
# name = "Search"
# url = "/search/"
# weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
# taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.victoria-ordonez]
default = true
email = "vordonez6@gatech.edu"
name = "Victoria Ordonez"
url = "https://vordonez6.github.io/shaping-quantum"

# [params.authors.will-faught]
# default = true
# email = "vordonez6@gatech.edu"
# name = "Victoria Ordonez"
# url = "https://willfaught.com/paige"

# [params.paige.git]
# commit_url = "https://github.com/willfaught/paige/commit/%s"

# [[params.paige.feed.atom.authors]]
# email = "will.faught@example.com"
# name = "Will Faught"
# url = "https://willfaught.com/paige"

# [params.paige.feed.rss]
# managing_editor = "will.faught@example.com (Will Faught)"
# web_master = "will.faught@example.com (Will Faught)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/vordonez6/shaping-quantum/tree/main/content%s"

#config.toml
#[[module.imports]]
#  path = "../static/"

#[taxonomies]
#author = "authors"
#category = "categories"
#series = "series"
#tag = "tags"



